
networks:
    nginx-php74-mysql8-node:

services:

    # nginx
    nginx-service:
        image: vitorium14/nginx:latest
        container_name: nginx-container
        ports:
            - "8080:80"
        volumes:
            - ./PIS:/var/www/project
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php74-service
        networks:
            - nginx-php74-mysql8-node

    # php
    php74-service:
        image: vitorium14/symfony-app:latest
        container_name: php-container
        ports:
            - "9000:9000"
        volumes:
            - ./PIS:/var/www/project
        networks:
            - nginx-php74-mysql8-node