services:
  php:
    image: vitorium14/symfony-app:latest
    container_name: symfony_app
    restart: always
    working_dir: /var/www/html
    # volumes:
    #   - .:/var/www/html

  nginx:
    image: vitorium14/symfony-nginx:latest
    container_name: symfony_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    depends_on:
      php:
        condition: service_started