version: '3.8'

services:
  app:
    build: .
    container_name: symfony_app
    restart: always
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=prod
      - APP_DEBUG=0

  webserver:
    image: nginx:alpine
    container_name: symfony_nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
