name: Deploy Symfony App

on:
  push:
    branches:
      - despliegueDocker

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código fuente
        uses: actions/checkout@v3

      - name: Iniciar sesión en Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Desplegar en servidor remoto
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_KEY }}
          script: |
              mkdir -p ~/deploy/symfony
              cd ~/deploy/symfony
              
              # Si ya existe, limpiamos los archivos antiguos
              rm -rf ~/deploy/symfony/*

      - name: Copiar archivos al servidor
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_KEY }}
          source: |
            ./PIS/compose.yml
            ./nginx/default.conf
          target: "~/deploy/symfony"

      - name: Ejecutar Docker Compose en el servidor
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_KEY }}
          script: |
                cd ~/deploy/symfony
                sudo docker compose pull
                sudo docker compose down
                sudo docker compose up -d --remove-orphans
                sudo docker system prune -f  # Limpieza de imágenes antiguas