name: Deploy Symfony API with MySQL and Nginx

on:
    push:
        branches:
            - despliegueDocker

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout código
              uses: actions/checkout@v4

            - name: Iniciar sesión en Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            # Construir y subir imagen Symfony
            - name: Construir y subir imagen Symfony
              run: |
                  cd PIS/php
                  docker build -t ${{ secrets.DOCKER_USERNAME }}/symfony-app:latest .
                  docker push ${{ secrets.DOCKER_USERNAME }}/symfony-app:latest

    deploy:
        runs-on: ubuntu-latest
        needs: build-and-push
        steps:
            - name: Checkout código
              uses: actions/checkout@v4
              with:
                  ref: despliegueDocker # Asegura que se usa esta rama

            - name: Transferir el archivo compose.yml al servidor remoto
              uses: appleboy/scp-action@master
              with:
                  host: ${{ secrets.REMOTE_HOST }}
                  username: ${{ secrets.REMOTE_USER }}
                  key: ${{ secrets.REMOTE_KEY }}
                  source: ./compose.yml
                  target: ~/deploy/

            - name: Desplegar en servidor remoto
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.REMOTE_HOST }}
                  username: ${{ secrets.REMOTE_USER }}
                  key: ${{ secrets.REMOTE_KEY }}
                  script: |
                     cd ~/deploy
                     ls -R
                     sudo chmod 666 /var/run/docker.sock
                     docker compose down || true
                     docker compose pull
                     docker compose up -d
