name: Deploy Symfony App

on:
  push:
    branches:
      - despliegueDocker

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código fuente
        uses: actions/checkout@v3

      - name: Iniciar sesión en Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Construir y subir imagen a Docker Hub
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/symfony-app:latest ./PIS
          docker push ${{ secrets.DOCKER_USERNAME }}/symfony-app:latest

      - name: Desplegar en servidor remoto
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
              mkdir -p ~/deploy/symfony
              cd ~/deploy/symfony
              
              # Si ya existe, limpiamos los archivos antiguos
              rm -rf ~/deploy/symfony/*

      - name: Copiar archivos al servidor
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "./PIS/compose.yml"
          target: "~/deploy/symfony"

      - name: Ejecutar Docker Compose en el servidor
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
                cd ~/deploy/symfony
                docker compose pull
                docker compose down
                docker compose up -d --remove-orphans
                docker system prune -f  # Limpieza de imágenes antiguas